services:
  # Backend API Service
  - type: web
    name: buckys-menu-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false

# Note: Cron jobs are handled by GitHub Actions (see .github/workflows/)
# - daily.yml: Runs menu fetch at 4 AM Central (10:00 UTC)
# - notifications.yml: Runs email notifications at 8 AM Central (14:00 UTC)
