name: Daily Menu Job

on:
  # Run once daily at 4:00 AM Central Time (10:00 UTC during DST, 9:00 UTC during standard time)
  # Using 10:00 UTC to account for Central Daylight Time
  schedule:
    - cron: "0 10 * * *"
  # Allow manual runs from the GitHub UI
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run daily menu job
        run: npm run job:daily
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
