name: Daily Email Notifications

on:
  # Run daily at 8:00 AM Central Time (14:00 UTC during DST, 13:00 UTC during standard time)
  # Using 14:00 UTC to account for Central Daylight Time
  # This runs 4 hours after the menu fetch job to ensure fresh data is available
  schedule:
    - cron: "0 14 * * *"
  # Allow manual runs from the GitHub UI
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  send-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Send email notifications
        run: npx tsx scripts/notificationJob.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}